### ISSUE TITLE
Typo in default values

### ISSUE THREAD

**Issue by dan-khamitov** [n0nSmoker/apg#4]
https://github.com/n0nSmoker/apg/blob/9158e3e4d9ea366f3fd134b8b6f909d0e1a0dbfa/apg/templates/flask/framework/cookiecutter.json#L2

https://github.com/n0nSmoker/apg/blob/9158e3e4d9ea366f3fd134b8b6f909d0e1a0dbfa/apg/templates/aiohttp/framework/cookiecutter.json#L2

**Comment by PlaNOid** [comment]
fixed
